title: LP Devs Blog
description: Sharing experiences about programming.

url: https://mobxa.github.io
baseurl: ""
permalink: blog/:title/

theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: lpdevs
   twitter: lpdevss
   facebook: lpdevs
   email: lampv606@gmail.com

google_analytics: ""
